spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://101.34.7.58:33061/mall?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  redis:
    host: 101.34.7.58
    port: 6379
    password: foobar32ed123
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations:
    - classpath*:/com/lh/mall/ums/mapper/xml/*.xml
  type-aliases-package: com.lh.mall.ums.entity
#    - com.lh.mall.ums.mapper.UmsMemberMapper

