
#????????https??????????????????
server:
  ssl:
    key-store: classpath:lhmall-alias.keystore
    key-store-type: JKS
    key-store-password: 123456
    key-alias: lhmall-alias
    key-password: 123456
---
spring:
  profiles:
    active: dev-ssl
server:
  port: 81