
#????????https??????????????????
server:
  ssl:
    key-store: classpath:lhmal-alias.keystore
    key-store-type: JKS
    key-store-password: 123456
    key-alias: lhmal-alias
    key-password: 123456
  port: 81
  http-port: 82
---
spring:
  profiles:
    active: dev-ssl